### ISSUE TITLE
This Doesn't Work

### ISSUE THREAD

**Issue by dlinch** [stephen31/virtual-keyboard-plugin#3]
I attempted to get your plugin to work, and it just doesn't. I even spun up a vanilla hello world example with both the local node_module and the cdn implementation, neither works. The source code is a mess of Webpack transpilation so I can't even reason through the source to figure out why it's not working, and there's no console errors to point me in the right direction.

I was excited because the directions were easy to use, and didn't require me to invoke the keyboard on the element like this [one](https://github.com/Mottie/Keyboard) but now I fear it's just masking any errors. I followed them to the letter and nothing is happening when I click my virtual-keyboard-hook div.

Here is the simple example that I couldn't get to work:
```<!DOCTYPE html>
<html>
  <head>
      <link rel="stylesheet" href="./node_modules/virtual-keyboard-plugin/dist/virtual-keyboard.css">
      <link rel="stylesheet" href="./node_modules/font-awesome/css/font-awesome.min.css">
      <script src="./node_modules/virtual-keyboard-plugin/dist/virtual-keyboard.js"></script>
  </head>
  <body>
    <h1>Stuff</h1>
    <input type="text" id="keyboard_uniq" virtual-keyboard/>
    <div class="virtual-keyboard-hook" data-target-id="keyboard_uniq" data-keyboard-mapping="qwerty"><i class="fa fa-keyboard-o" aria-hdden="true"></i></div>
  </body>
</html>
```

**Comment by stephen31** [comment]
Hello dlinch,

you have to put the script after the body tag on your html like this : 
```
<html>
  <head>
      <link rel="stylesheet" href="./node_modules/virtual-keyboard-plugin/dist/virtual-keyboard.css">
      <link rel="stylesheet" href="./node_modules/font-awesome/css/font-awesome.min.css">
  </head>
  <body>
    <h1>Stuff</h1>
    <input type="text" id="keyboard_uniq" virtual-keyboard/>
    <div class="virtual-keyboard-hook" data-target-id="keyboard_uniq" data-keyboard-mapping="qwerty"><i class="fa fa-keyboard-o" aria-hdden="true"></i></div>
  </body>
   <script src="./node_modules/virtual-keyboard-plugin/dist/virtual-keyboard.js"></script>
</html>
```
