### ISSUE TITLE
virtual-keyboard-plugin doesnt launch on DomContentLoaded listener

### ISSUE THREAD

**Issue by MeghanaRedd** [stephen31/virtual-keyboard-plugin#6]
I am using polymerjs in my project which primarily works with web components. I have integrated virtual-keyboard-plugin in one of my elements. However, the listener on domContentLoaded doesn't get fired, thus not rendering the virtual keyboard on the page. I observed that when I use WebComponentsReady instead of domContentLoaded (in virtual-keyboard.js), the event listener fires.
               Is there a way that I can work with domContentLoaded without modifying the library?

**Comment by stephen31** [comment]
thank you for the feedback  , i will probably add the support of WebComponentsReady  event on the next release of the library. stay tuned

**Comment by stephen31** [comment]
the WebComponentsReady event is now supported on the v1.2.0 of the library
